spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/tyresg142
    username: postgres
    password: qwerty
  application:
    name: restG142
server:
  port: 8083